services:
  livro:
    build:
      context: .
    image: bases5-ciencia-de-dados:local
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - HOME=/tmp
    ports:
      - "4201:4201"
    volumes:
      - .:/livro
